# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/br41n-ecog-hand-pose',
                'doc_host': 'https://bkowshik.github.io',
                'git_url': 'https://github.com/bkowshik/br41n-ecog-hand-pose',
                'lib_path': 'br41n_ecog_hand_pose'},
  'syms': { 'br41n_ecog_hand_pose.data': { 'br41n_ecog_hand_pose.data.ECoGRecording': ( 'data_loading.html#ecogrecording',
                                                                                        'br41n_ecog_hand_pose/data.py'),
                                           'br41n_ecog_hand_pose.data.ECoGRecording.duration_s': ( 'data_loading.html#ecogrecording.duration_s',
                                                                                                   'br41n_ecog_hand_pose/data.py'),
                                           'br41n_ecog_hand_pose.data.ECoGRecording.n_samples': ( 'data_loading.html#ecogrecording.n_samples',
                                                                                                  'br41n_ecog_hand_pose/data.py'),
                                           'br41n_ecog_hand_pose.data._find_default_path': ( 'data_loading.html#_find_default_path',
                                                                                             'br41n_ecog_hand_pose/data.py'),
                                           'br41n_ecog_hand_pose.data.load_ecog': ( 'data_loading.html#load_ecog',
                                                                                    'br41n_ecog_hand_pose/data.py')}}}
