# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/br41n-ecog-hand-pose',
                'doc_host': 'https://bkowshik.github.io',
                'git_url': 'https://github.com/bkowshik/br41n-ecog-hand-pose',
                'lib_path': 'br41n_ecog_hand_pose'},
  'syms': {}}
