"""Train and evaluate baseline classifiers (LDA, SVM, logistic regression) on the multi-band-power features using stratified k-fold cross-validation."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/06_classification.ipynb.

# %% auto #0
__all__ = ['CLASSIFIERS', 'make_pipeline', 'cross_validate']

# %% ../nbs/06_classification.ipynb #6ad5310b
import numpy as np
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

# %% ../nbs/06_classification.ipynb #7fec6f37
CLASSIFIERS = {
    'LDA':      lambda: LinearDiscriminantAnalysis(shrinkage='auto', solver='lsqr'),
    'SVM-rbf':  lambda: SVC(kernel='rbf', C=1.0, gamma='scale'),
    'logreg':   lambda: LogisticRegression(max_iter=2000, C=1.0),
}

# %% ../nbs/06_classification.ipynb #c483698d
def make_pipeline(clf):
    """Standardize, then classify."""
    return Pipeline([('scale', StandardScaler()), ('clf', clf)])

def cross_validate(make_clf, X, y, n_splits=5, random_state=0):
    """Stratified k-fold accuracy + summed confusion matrix.

    `make_clf` is a no-arg callable returning a fresh classifier per fold.
    Returns `(per_fold_accuracy, summed_confusion_matrix, class_labels)`."""
    classes = np.unique(y)
    skf = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    accs, cm_total = [], np.zeros((len(classes), len(classes)), dtype=int)
    for tr, te in skf.split(X, y):
        clf = make_pipeline(make_clf())
        clf.fit(X[tr], y[tr])
        pred = clf.predict(X[te])
        accs.append(accuracy_score(y[te], pred))
        cm_total += confusion_matrix(y[te], pred, labels=classes)
    return np.array(accs), cm_total, classes
