"""Load the raw `ECoG_Handpose.mat` file and expose helpers to access the time, 60-channel ECoG, paradigm-label, and 5-finger data-glove channels."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_data_loading.ipynb.

# %% auto #0
__all__ = ['FS', 'TIME_ROW', 'ECOG_ROWS', 'LABEL_ROW', 'GLOVE_ROWS', 'GESTURE_NAMES', 'FINGER_NAMES', 'ECoGRecording',
           'load_ecog']

# %% ../nbs/01_data_loading.ipynb #b3761f2e
from dataclasses import dataclass
from pathlib import Path
import numpy as np
from scipy.io import loadmat

# %% ../nbs/01_data_loading.ipynb #ea5608e7
FS = 1200                       # sampling frequency, Hz
TIME_ROW   = 0                  # CH1   — sample time
ECOG_ROWS  = slice(1, 61)       # CH2-61 — 60 ECoG channels
LABEL_ROW  = 61                 # CH62  — paradigm label
GLOVE_ROWS = slice(62, 67)      # CH63-67 — 5 finger glove channels

GESTURE_NAMES = {0: 'relax', 1: 'fist', 2: 'peace', 3: 'open'}
FINGER_NAMES = ['thumb', 'index', 'middle', 'ring', 'little']

# %% ../nbs/01_data_loading.ipynb #f7271368
@dataclass
class ECoGRecording:
    "Container for the rock-paper-scissors ECoG dataset."
    time:   np.ndarray   # (T,)
    ecog:   np.ndarray   # (60, T)
    labels: np.ndarray   # (T,) int — paradigm code per sample
    glove:  np.ndarray   # (5, T) — finger flexion per sample
    fs:     float = FS

    @property
    def n_samples(self):  return self.ecog.shape[1]

    @property
    def duration_s(self): return self.n_samples / self.fs

# %% ../nbs/01_data_loading.ipynb #0efb936b
def _find_default_path():
    rel = Path('data/ECoG_Handpose.mat')
    for parent in [Path.cwd(), *Path.cwd().parents]:
        if (parent / rel).exists(): return parent / rel
    raise FileNotFoundError(f'ECoG_Handpose.mat not found above {Path.cwd()}')

# %% ../nbs/01_data_loading.ipynb #6fec18cb
def load_ecog(path=None):
    "Load `ECoG_Handpose.mat` and return an `ECoGRecording`."
    path = Path(path) if path else _find_default_path()
    y = loadmat(str(path))['y']
    return ECoGRecording(
        time   = y[TIME_ROW],
        ecog   = y[ECOG_ROWS],
        labels = y[LABEL_ROW].astype(int),
        glove  = y[GLOVE_ROWS],
    )
