"""Detect cue onsets from CH62 (paradigm channel) and segment continuous, preprocessed ECoG into per-trial epochs aligned to gesture cue."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_epoching.ipynb.

# %% auto #0
__all__ = ['find_cue_onsets', 'epoch', 'epoch_recording']

# %% ../nbs/04_epoching.ipynb #3d78b762
import numpy as np

# %% ../nbs/04_epoching.ipynb #7db900eb
def find_cue_onsets(labels):
    """Return (onsets, classes) — sample indices and gesture codes for every cue in `labels`."""
    labels = np.asarray(labels)
    onsets = np.where((labels[1:] != 0) & (labels[:-1] == 0))[0] + 1
    classes = labels[onsets]
    return onsets, classes

# %% ../nbs/04_epoching.ipynb #73d769bc
def epoch(x, onsets, fs, tmin=-0.5, tmax=2.0):
    """Slice (channels, time) array `x` into (n_trials, channels, n_samples) epochs.

    Returns `(epochs, kept_mask)` — `kept_mask` is True for onsets whose window fit."""
    a = int(round(tmin * fs))
    b = int(round(tmax * fs))
    n_samples = b - a
    T = x.shape[-1]
    kept = (onsets + a >= 0) & (onsets + b <= T)
    starts = onsets[kept] + a
    epochs = np.stack([x[..., s:s + n_samples] for s in starts])
    return epochs, kept

# %% ../nbs/04_epoching.ipynb #a63c7d16
def epoch_recording(rec, tmin=-0.5, tmax=2.0, signal=None):
    """Epoch `signal` (defaults to `rec.ecog`) using cues from `rec.labels`."""
    x = rec.ecog if signal is None else signal
    onsets, classes = find_cue_onsets(rec.labels)
    epochs, kept = epoch(x, onsets, rec.fs, tmin=tmin, tmax=tmax)
    return epochs, classes[kept]
