"""Compute features known to be informative for motor decoding from ECoG: band power in mu (8–12 Hz), beta (13–30 Hz), low-gamma (30–70 Hz), and high-gamma (70–170 Hz) ranges."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_features.ipynb.

# %% auto #0
__all__ = ['BANDS', 'band_power', 'multi_band_power', 'zscore_fit', 'zscore_apply']

# %% ../nbs/05_features.ipynb #c7b17642
import numpy as np
from scipy.signal import welch

# %% ../nbs/05_features.ipynb #9722be33
BANDS = {
    'mu':         (8, 12),
    'beta':       (13, 30),
    'low_gamma':  (30, 70),
    'high_gamma': (70, 170),
}

# %% ../nbs/05_features.ipynb #be92a597
def band_power(x, fs, low, high, nperseg=None):
    """Mean PSD power in `[low, high]` Hz along the last axis of `x`."""
    n = x.shape[-1] if nperseg is None else min(nperseg, x.shape[-1])
    freqs, psd = welch(x, fs=fs, nperseg=n, axis=-1)
    mask = (freqs >= low) & (freqs <= high)
    return psd[..., mask].mean(axis=-1)

# %% ../nbs/05_features.ipynb #320ab3aa
def multi_band_power(epochs, fs, bands=None, log=True):
    """Concatenate band-power features over `bands` along the last axis."""
    bands = BANDS if bands is None else bands
    feats = []
    for low, high in bands.values():
        bp = band_power(epochs, fs, low, high)
        feats.append(np.log(bp + 1e-12) if log else bp)
    return np.concatenate(feats, axis=-1)

# %% ../nbs/05_features.ipynb #476b7acd
def zscore_fit(X):
    """Return `(mean, std)` along axis 0 for later application via `zscore_apply`."""
    return X.mean(axis=0), X.std(axis=0) + 1e-12

def zscore_apply(X, stats):
    mean, std = stats
    return (X - mean) / std
