"""Standard ECoG cleaning pipeline: notch filter for line-noise harmonics, bandpass to the relevant frequencies, and common average referencing across the 60-channel grid."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/03_preprocessing.ipynb.

# %% auto #0
__all__ = ['notch_filter', 'bandpass', 'common_average_reference', 'find_bad_channels', 'preprocess']

# %% ../nbs/03_preprocessing.ipynb #1874869c
import numpy as np
from scipy.signal import iirnotch, butter, filtfilt

# %% ../nbs/03_preprocessing.ipynb #ad2be62a
def notch_filter(x, fs, freq=50.0, Q=30.0, harmonics=3):
    """Zero-phase IIR notch at `freq` (and `harmonics` overtones) on a (channels, time) array."""
    out = x
    for k in range(1, harmonics + 1):
        f = freq * k
        if f >= fs / 2: break
        b, a = iirnotch(f, Q, fs=fs)
        out = filtfilt(b, a, out, axis=-1)
    return out

# %% ../nbs/03_preprocessing.ipynb #2fb5330e
def bandpass(x, fs, low=1.0, high=200.0, order=4):
    """Zero-phase Butterworth bandpass on a (channels, time) array."""
    b, a = butter(order, [low, high], btype='band', fs=fs)
    return filtfilt(b, a, x, axis=-1)

# %% ../nbs/03_preprocessing.ipynb #9d4234c5
def common_average_reference(x):
    """Subtract the across-channel mean from each sample of `x` (channels, time)."""
    return x - x.mean(axis=0, keepdims=True)

# %% ../nbs/03_preprocessing.ipynb #bcb348e4
def find_bad_channels(x, threshold=5.0):
    """Return the indices of channels whose std is `threshold` MADs from the median std."""
    s = x.std(axis=1)
    med = np.median(s)
    mad = np.median(np.abs(s - med)) + 1e-12
    return np.where(np.abs(s - med) / mad > threshold)[0]

# %% ../nbs/03_preprocessing.ipynb #5e4d6d8f
def preprocess(ecog, fs, line_freq=50.0, line_harmonics=3, band=(1.0, 200.0), bad_threshold=5.0):
    """Notch (with harmonics) → bandpass → zero out bad channels → CAR."""
    y = notch_filter(ecog, fs, freq=line_freq, harmonics=line_harmonics)
    y = bandpass(y, fs, *band)
    bad = find_bad_channels(y, threshold=bad_threshold)
    y[bad] = 0.0
    y = common_average_reference(y)
    return y, bad
