"""Use the data-glove channels (CH63–67, one per finger) as continuous targets and decode finger flexion from ECoG, instead of treating gesture as a discrete label."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/08_finger_regression.ipynb.

# %% auto #0
__all__ = ['glove_targets', 'cross_validate_regression']

# %% ../nbs/08_finger_regression.ipynb #imports
import numpy as np
from scipy.stats import pearsonr
from sklearn.linear_model import Ridge
from sklearn.model_selection import KFold
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from .epoching import find_cue_onsets, epoch

# %% ../nbs/08_finger_regression.ipynb #targets-code
def glove_targets(rec, tmin=0.0, tmax=2.0):
    """Return `(targets, kept)`: mean flexion per finger per kept trial."""
    onsets, _ = find_cue_onsets(rec.labels)
    epochs, kept = epoch(rec.glove, onsets, rec.fs, tmin=tmin, tmax=tmax)
    return epochs.mean(axis=-1), kept   # (trials, 5)

# %% ../nbs/08_finger_regression.ipynb #ridge-code
def cross_validate_regression(X, Y, alpha=1.0, n_splits=5, random_state=0):
    """K-fold CV of Ridge regression. Returns `(corrs, mses)` shaped `(folds, n_targets)`."""
    kf = KFold(n_splits=n_splits, shuffle=True, random_state=random_state)
    n_targets = Y.shape[1]
    corrs, mses = [], []
    for tr, te in kf.split(X):
        model = Pipeline([('scale', StandardScaler()), ('reg', Ridge(alpha=alpha))])
        model.fit(X[tr], Y[tr])
        pred = model.predict(X[te])
        corrs.append([pearsonr(pred[:, i], Y[te, i])[0] for i in range(n_targets)])
        mses.append(((pred - Y[te]) ** 2).mean(axis=0))
    return np.array(corrs), np.array(mses)
